"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _route_dashboard from './route-dashboard.bones.json'
import _route_breakdown from './route-breakdown.bones.json'
import _route_invoices from './route-invoices.bones.json'
import _route_reports from './route-reports.bones.json'
import _route_accountant from './route-accountant.bones.json'
import _route_connect from './route-connect.bones.json'

registerBones({
  "route-dashboard": _route_dashboard,
  "route-breakdown": _route_breakdown,
  "route-invoices": _route_invoices,
  "route-reports": _route_reports,
  "route-accountant": _route_accountant,
  "route-connect": _route_connect,
})
