/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BillingEmail {
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp;
  id: Generated<Int8>;
  /**
   * provider message id, used for idempotency
   */
  message_id: string;
  recipient_id: Int8;
  server_id: Int8;
  subject: string | null;
}

export interface BillingInvoiceLineItems {
  /**
   * line amount in minor units (cents)
   */
  amount: Int8;
  description: string;
  id: Generated<Int8>;
  invoice_id: Int8;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  quantity: Numeric | null;
  /**
   * unit rate in minor units (cents); null for flat/zero-rate lines
   */
  rate: Int8 | null;
  unit: string | null;
}

export interface BillingInvoices {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  due_date: Timestamp | null;
  email_id: Int8;
  failure_reason: string | null;
  id: Generated<Int8>;
  invoice_date: Timestamp | null;
  invoice_number: string | null;
  org_id: Int8;
  /**
   * GridFS file id in MongoDB; null until fetched
   */
  pdf_id: string | null;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  status: Generated<string>;
  /**
   * total amount in minor units (cents)
   */
  value: Generated<Int8>;
}

export interface ClientAccount {
  connected_at: Generated<Timestamp>;
  email_address: string;
  id: Generated<Int8>;
  org_id: Int8;
  provider: string;
  refresh_token_encrypted: string;
  status: Generated<string>;
}

export interface ClientBillingAddress {
  address: string;
  id: Generated<Int8>;
  org_id: Int8;
}

export interface ClientOrg {
  id: Generated<Int8>;
  name: string;
}

export interface ServerService {
  id: Generated<Int8>;
  name: string;
  sender_address: string;
}

export interface DB {
  "billing.email": BillingEmail;
  "billing.invoice_line_items": BillingInvoiceLineItems;
  "billing.invoices": BillingInvoices;
  "client.account": ClientAccount;
  "client.billing_address": ClientBillingAddress;
  "client.org": ClientOrg;
  "server.service": ServerService;
}
