/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BillingEmail {
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp;
  id: Generated<Int8>;
  /**
   * provider message id, used for idempotency
   */
  message_id: string;
  recipient_id: Int8;
  server_id: Int8;
  subject: string | null;
}

export interface BillingInvoiceLineItems {
  /**
   * line amount in minor units (cents)
   */
  amount: Int8;
  /**
   * usage category; null until classified
   */
  category: string | null;
  description: string;
  id: Generated<Int8>;
  invoice_id: Int8;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  quantity: Numeric | null;
  /**
   * unit rate in minor units (cents); null for flat/zero-rate lines
   */
  rate: Int8 | null;
  /**
   * origin of the itemization: parsed invoice, or an optional vendor API connection
   */
  source: Generated<string>;
  unit: string | null;
}

export interface BillingInvoices {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  due_date: Timestamp | null;
  email_id: Int8;
  failure_reason: string | null;
  id: Generated<Int8>;
  invoice_date: Timestamp | null;
  invoice_number: string | null;
  org_id: Int8;
  /**
   * GridFS file id in MongoDB; null until fetched
   */
  pdf_id: string | null;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  status: Generated<string>;
  /**
   * total amount in minor units (cents)
   */
  value: Generated<Int8>;
}

export interface ClientAccount {
  connected_at: Generated<Timestamp>;
  email_address: string;
  id: Generated<Int8>;
  org_id: Int8;
  provider: string;
  refresh_token_encrypted: string;
  status: Generated<string>;
}

export interface ClientApiKey {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<Int8>;
  /**
   * sha256 hex of the raw key; the raw key is never stored
   */
  key_hash: string;
  key_prefix: string;
  last_used_at: Timestamp | null;
  name: Generated<string>;
  org_id: Int8;
  revoked_at: Timestamp | null;
}

export interface ClientAuthAccount {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ClientAuthSession {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface ClientAuthUser {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface ClientAuthVerification {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface ClientBillingAddress {
  address: string;
  id: Generated<Int8>;
  org_id: Int8;
}

export interface ClientOrg {
  /**
   * currency the budget is denominated in; sums are never converted
   */
  budget_currency: string | null;
  /**
   * display currency a workspace opens on; null falls back to the busiest currency in the data
   */
  default_currency: string | null;
  /**
   * single: the org is one budget unit. multi: spend is attributable to teams (SPEC.md)
   */
  department_mode: Generated<string>;
  /**
   * first calendar month of the fiscal year; fiscal years are named for the year they end in
   */
  fiscal_year_start_month: Generated<number>;
  id: Generated<Int8>;
  /**
   * monthly spend budget in minor units (cents); null when unset
   */
  monthly_budget_minor: Int8 | null;
  name: string;
}

export interface ClientOrgInvitation {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Generated<Timestamp>;
  id: Generated<Int8>;
  invited_by: string | null;
  org_id: Int8;
  role: Generated<string>;
  status: Generated<string>;
}

export interface ClientOrgMember {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  org_id: Int8;
  role: Generated<string>;
  user_id: string;
}

export interface ClientUserActiveOrg {
  org_id: Int8;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ServerService {
  id: Generated<Int8>;
  name: string;
  sender_address: string;
}

export interface DB {
  "billing.email": BillingEmail;
  "billing.invoice_line_items": BillingInvoiceLineItems;
  "billing.invoices": BillingInvoices;
  "client.account": ClientAccount;
  "client.api_key": ClientApiKey;
  "client.auth_account": ClientAuthAccount;
  "client.auth_session": ClientAuthSession;
  "client.auth_user": ClientAuthUser;
  "client.auth_verification": ClientAuthVerification;
  "client.billing_address": ClientBillingAddress;
  "client.org": ClientOrg;
  "client.org_invitation": ClientOrgInvitation;
  "client.org_member": ClientOrgMember;
  "client.user_active_org": ClientUserActiveOrg;
  "server.service": ServerService;
}
