import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MotionConfig } from 'framer-motion';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { App } from './App';
import { ThemeProvider } from './state/theme';
/*
 * Captured skeleton bones, generated by `boneyardPlugin` in vite.config.ts and
 * committed. Imported once here: the registry is what lets `<Skeleton name="…">`
 * resolve a shape without every caller passing measurements around.
 */
import './bones/registry';
import './index.css';

/*
 * Safari on iOS only dispatches :active if the element or one of its ancestors
 * carries a touch listener. One no-op listener buys press feedback for the
 * whole app; without it every .press control is dead on iPhone.
 */
document.addEventListener('touchstart', () => {}, { passive: true });

/*
 * Boneyard measures the real UI, and every page here is behind auth and a
 * database — so a headless capture would otherwise get the signed-out
 * marketing page. This stubs `/api/*` before the first render, and only when
 * the capture flag is set. The dynamic import keeps it out of the production
 * bundle entirely rather than shipping a dormant branch.
 */
if (import.meta.env.DEV) {
  const { installBonesFixtures, isCapturing } = await import('./dev/bones-fixtures');
  installBonesFixtures();
  if (isCapturing()) {
    const { patchBonesSnapshot } = await import('./dev/bones-snapshot');
    patchBonesSnapshot();
  }
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: { staleTime: 30_000, refetchOnWindowFocus: false },
  },
});

const rootEl = document.getElementById('root');
if (rootEl) {
  createRoot(rootEl).render(
    <StrictMode>
      {/* every motion.* component drops transforms and keeps opacity when the
          user asks for reduced motion, without each one re-checking */}
      <MotionConfig reducedMotion="user">
        <ThemeProvider>
          <QueryClientProvider client={queryClient}>
            <BrowserRouter>
              <App />
            </BrowserRouter>
          </QueryClientProvider>
        </ThemeProvider>
      </MotionConfig>
    </StrictMode>,
  );
}
